### ISSUE TITLE
News item image

### ISSUE THREAD

**Issue by jazzchatfield** [GenderedIntelligence/the-trans-dimension#137]
## Description
- Use image from PlaceCal or 

Randomise default images for news posts without a designated image
- News items need to have 1 of 6 possible default items if they don't have a set image. (Some of this depends on how the back-end news is gonna work.)

**Proposal:** A function that picks an image from 1 to 6 based on the date of the news post, so they will remain consistent on rebuilds.

**Comment by katjam** [comment]
@ivan-kocienski-gfsc maybe this one?

**Comment by katjam** [comment]
Reopening - so we can verify if it isworking

**Comment by katjam** [comment]
@ivan-kocienski-gfsc Can you check if this is working as you expected following the https:// fix

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/195383356-95db174c-e972-40c7-a366-131d1aa07e08.png)

**Comment by katjam** [comment]
We need to do a PlaceCal deploy - then verify & close this.

**Comment by erbridge** [comment]
News images appear to now be picked up and rendered.
