### ISSUE TITLE
[Bug]: Adobe font kit doesn't contain all the required fonts

### ISSUE THREAD

**Issue by jazzchatfield** [GenderedIntelligence/the-trans-dimension#183]
## Description

The typekit we were previously using didn't contain a bunch of the needed font types e.g. Covik Sans Black.

Temporarily replaced this with my own in PR #179 but if we are sticking with GI using their Adobe account we will need to get them to update their Adobe project with the additional fonts.

I can produce a list of which styles exactly are needed so we don't load in any superfluous ones - I am going to make a separate ticket to comb the site for fonts anyway, so a list can be produced out of that.

## Steps to reproduce
1. Switch to the old font kit link.
2. Look at the date/time on Event pages and compare to the version using my temporary link, which more closely matches the design specs.

## Acceptance criteria

- [ ] All fonts used on the site are imported correctly
- [ ] We are using GI owned resources for fonts (eg their TypeKit not gfsc's) - https://use.typekit.net/qwi3qrw.css

**Comment by katjam** [comment]
No. It's on my checklist though.

**Comment by erbridge** [comment]
Kim's making the request. Thanks Katja.

**Comment by erbridge** [comment]
This TypeKit has the fonts in it and the right owners: https://use.typekit.net/qwi3qrw.css
