### ISSUE TITLE
[Bug]: Partner id list ---> author name not rendering for news articles 

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#202]
## Description
- check News listing, individual news item & meta description for news item
- If partner id is optional - do not print bullet if there are no partners. If it is required, parse the expected field.

## Acceptance Criteria

- [ ] I can see partner name in the news listing teasers
- [ ] I can see partner name in the news item page

**Comment by katjam** [comment]
Move back to release priority because of design note:
News (on homepage too) [All states]
The bullet in front of the date should only appear if we’re having authors, if we’re losing authors please drop this.

**Comment by katjam** [comment]
Current news stories do not have partner Ids.

Need to check if this is intentional or we are lookin in the wrong place.

**Comment by katjam** [comment]
@kimadactyl @ivankocienski Just checking if we intend to leave partner field on articles optional, if so I will handle the empty case.

I have added partners to the 3 articles @GeorgieMcVicar wrote because it was obvious which organisation they belonged to.

**Comment by kimadactyl** [comment]
They should have partners but I think how it is they don't have to. This is open to discussion and happy to do whatever's simpler.
