### ISSUE TITLE
Link to event on single event page

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#223]
## Acceptance criteria
- [ ] I can go to the event page (outside of PlaceCal & Trans Dimension) if the event has a url associated with it
- [ ] I can see the event link in the Event address section

## Implementation notes & questions
- Use same pattern as maybeUrl for EventPartner
- id 290521, 290522 have one `publisherUrl`

**Comment by katjam** [comment]
@ivankocienski Are we in a place where I can rely on there being a distinguishable event url in the placecal data?

**Comment by erbridge** [comment]
@katjam Can you elaborate on your concerns about link verification, please?

**Comment by katjam** [comment]
@erbridge Yes - because the event info is auto-generated data, I wanted to make sure that:

1 -the field that comes from PlaceCal that says it's an event url is always a well-formed url
2- the well-formed url actually links to something (not broken) and that thing is the event (not something else)

**Comment by ivan-kocienski-gfsc** [comment]
@katjam are you talking about events [onlineEventUrl](https://github.com/geeksforsocialchange/PlaceCal/blob/9837a4f91f6f53d78ab3731e6faf45e2c13c2414/app/graphql/types/event_type.rb#L41) as a source of this value?

**Comment by erbridge** [comment]
@ivan-kocienski-gfsc I think that's a reasonable assumption here. That looks like the thing that fits the (implicit) user story.
