### ISSUE TITLE
[Bug]: Small styling tweaks

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#241]
## Description
These are observations from testing

## Steps to reproduce

- [ ] Space between partners maybe a touch more on mobile?
- [ ] Check empty state styles for news: “there is no recent news” floating
- [ ] could do with more spacing above this find out more button on mobile & a bit more spacing around the placecal text too?

**Comment by kimadactyl** [comment]
this seems abandoned, closing
