### ISSUE TITLE
News Article list link UI

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#243]
## User story
As a person browsing news listing I need to be able to get to the full article easilty so that I am not frustrated

## Acceptance criteria
- [ ] The page meets accessibility standards
- [ ] Users are not confused by what is clickable and what is not

**Comment by kimadactyl** [comment]
Gonna put this on the v1.0 backlog in last place - its a tiny tweak but its really bugging me :)

I would also like the partner name ('velociposse') to link through?

Np if it doesnt happen - deffo a nice to have

**Comment by erbridge** [comment]
Suggest pulling the partner name linking into a new issue. It's not at all trivial to do right now (I just spent an hour making some progress on it, but not completing it).
