### ISSUE TITLE
Change the Join form settings for production

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#246]
## Acceptance criteria

- [x] Submissions to the join form go to info@transdimension.uk via email
- [ ] #315
- [x] The footer says "Join Us" not "Join" #255

**Comment by ivan-kocienski-gfsc** [comment]
Is [this](https://github.com/GenderedIntelligence/the-trans-dimension/blob/18d9e59735c1756c242aba44ee60f7d1406bd0a8/src/Page/JoinUs.elm#L164) the deployment URL?

Is the email in the first point configured in netlify?

**Comment by erbridge** [comment]
Not sure what a `deployment URL` is in the context of a form, but that does look like the POST target, yes @ivan-kocienski-gfsc.

**Comment by erbridge** [comment]
@ivan-kocienski-gfsc Kim confirms that the email is set up to go somewhere.

**Comment by ivan-kocienski-gfsc** [comment]
Yeah I guess i am saying that the AC specify a bunch of values need to be changed but give no indication as to what they should be changed to or where  those values are coming from. If this is known information then either put it in the issue or put a note here telling whomever picks it up where this information can be found.

"Oh just change the CDN URL" is unhelpful
