### ISSUE TITLE
Favicons should be sourced from canonical url https://transdimension.uk (staging until we flip dns)

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#247]
- Check they are working once live

See also #210 for complete set needs adding

note if we do #268 withconfigurable env vars for case url, this shoud make use of that

## Acceptance criteria

- [ ] Favicons are sourced from the canonical URL of the current environment (https://transdimension.uk on production)

**Comment by ivan-kocienski-gfsc** [comment]
This looks to be operating as described. The earlier issue #317 addresses this by removing the hard-coded value.
