### ISSUE TITLE
Complete design on homepage with blue info box

### ISSUE THREAD

**Issue by jazzchatfield** [GenderedIntelligence/the-trans-dimension#266]
## Description
I think the homepage looks janky with part of Mark's design missing. Can I add something back in there? Proposal for now (very rough copy):

```
Title: What is The Trans Dimension?
Small text: Find out more about us and why we exist.
Button text: About us
```

Then, when we have something more concrete to go in there - resources? - we can just swap it out.

## Plan

- [ ] See if @katjam agrees

**Comment by katjam** [comment]
@studiosquid 

Shall we...
1) add to the bottom of work queue, 2) close as a won't fix, 3) leave open for future niceness but not important now.

**Comment by studiosquid** [comment]
@katjam I think this is 2 and can be closed it's not broken as such. 
We've got the design ready to go if we ever need to add something impactful and extra to the design :)
