### ISSUE TITLE
Add web stats

### ISSUE THREAD

**Issue by kimadactyl** [GenderedIntelligence/the-trans-dimension#272]
## User story

As a fundraiser at GI I need stats on how many people use the site so that we can tell funders and sponsors how many visits we have.

As a fundraiser at GI I need stats on how many people went to LocalGiving via TransDimension so that we know roughly how much the site is making.

## Acceptance criteria

- [ ] Plausible tracks overall website stats
- [ ] We know how many people clicked on the "donate" button.

## Implementation notes & questions

Add plausible code as follows:

`<script defer data-domain="transdimension.uk" src="https://plausible.io/js/plausible.js"></script>`

LocalGiving does sadly not allow tracking codes.

**Comment by katjam** [comment]
@kimadactyl this is the Issue with AC about tracking donate. Closed but oddly unverified. Let's look into it further with this new milestone. We can hopefully make amends that mean we can track how much GI donation comes direct from transdimesion.uk
