### ISSUE TITLE
[Bug]: Event page URL links should not visibly include https://www. or www.

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#279]
## Design notes
- URL links should not visibly include https://www/. or [www](http://www/). on Event and Partners pages

## Acceptance TBC
- URL links should not visibly include protocol e.g. https://on Event and Partners pages 
- Url links should not include trailing /

**Comment by katjam** [comment]
@kimadactyl @jasminechatfield Mark has suggested we strip the protocol & www from the visible url text on an event page.

Do either of you have an opinion on whether that causes accessibility issues like copy -paste or forwarding screenshots to people containing the information?

**Comment by kimadactyl** [comment]
i've never heard a reason why and agree it looks a lot neater!
