### ISSUE TITLE
[Bug 2]: Partners page spacing does not match design

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#280]
## Design notes
- Description needs much more spacing from the top with or without a logo appearing. 
- Where there’s no description or logo I think we need a note saying “Description coming soon” and lots of healthy spacing as per the design to keep the get in touch / address bits from jumping right to the top.
- Spacing where there’s no map, and no events, need spacing between “Check back for updates! And the bottom of the box.

## Acceptance Criteria TBC
- [ ] Description spacing from top matches design
- [ ] If no description, there is spacing instead
- [ ] If no map, nor events, need spacing between "Check back.." and bottom

**Comment by katjam** [comment]
@kimadactyl @jasminechatfield I disagree with Mark's suggestion of adding "Description coming soon" if we expect Partners to provide this optionally. What do you think?

**Comment by kimadactyl** [comment]
agree yeah, we can't assume they will add it. "Ask {partnername} for more information"?
