### ISSUE TITLE
All events currently shows events starting with those in the past this is confusing.

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#282]
## User story
When viewing all events, I expect it to be future ones only, but I do need to be able to also access past events if I want to.

There are many ways we could acheive this and it's probably worth doing a bit of testing before we choose one.

## Implementation notes & questions
![image](https://user-images.githubusercontent.com/861172/169695129-44b0b8a2-9586-49b5-9087-4f103ec9742a.png)

**Comment by ivan-kocienski-gfsc** [comment]
Shouldn't this be a ticket for PC as TD is just pulling from that?

**Comment by ivan-kocienski-gfsc** [comment]
Okay [this](https://github.com/GenderedIntelligence/the-trans-dimension/blob/52b6a63e114ad679367857efccbeeb226ecb8b65/src/Data/PlaceCal/Events.elm#L117) looks like a problem

**Comment by katjam** [comment]
@ivan-kocienski-gfsc Check with @kimadactyl on desired behaviour. I think this ticket needed AC defined before you started the work.

It was clear in the User story that people need to be able to access past events if they want to. So maybe we need another button? Or just a scroll to the current day?

I also think the pagination really needs some usability testing with people before we spend too much time tinkering with it. For the launch, let's just agree some behaviour that is not terroble.
