### ISSUE TITLE
We’re in Beta banner with survey link - flash message style.

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#286]
## User story
As a {person} I need know the site is in beta so that I feel welcome to give feedback & do not expect it to be perfect

## Acceptance criteria
- [ ] There is a banner with a survey link inviting feedback on the site
- [ ] Appears on all pages until dismissed
- [ ] It is dismissable
- [ ] Banner is always present on a fresh load of the site

**Comment by kimadactyl** [comment]
i think there is but i don't have it to hand i can find it after quest if @jasminechatfield doesnt have it?

**Comment by katjam** [comment]
@ivankocienski I'll probably need to give you a steer on this one if you do want to tackle it. Maybe do the other's first?

**Comment by katjam** [comment]
Desktop:
![image](https://user-images.githubusercontent.com/861172/181239483-bd39e3b9-8979-4417-a7a0-1575b1732936.png)

Mobile:
![image](https://user-images.githubusercontent.com/861172/181239580-2646b46b-99db-4e37-bf4e-e537d610ead2.png)

**Comment by katjam** [comment]
https://github.com/GenderedIntelligence/the-trans-dimension/pull/293
