### ISSUE TITLE
Trigger a build every few hours on a cron

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#287]
## Acceptance Criteria

- [ ] The events ont the site are updates a few times a day

## Plan
https://docs.netlify.com/configure-builds/build-hooks

This triggers a build. We can use a cron on PlaceCal server to trigger it twice a day? Don't want to burn through build minutes.
curl -X POST https://api.netlify.com/build_hooks/62a3066ab986f708460f4428

**Comment by katjam** [comment]
@kimadactyl @ivankocienski I know we talked about this before, but since we don't have a server for Trans Dimension, it would be easiest if the cron was triggered from PlaceCal server since that is already set up. 

There maybe an alternative service we can ue, but I am not sure.

**Comment by katjam** [comment]
I had originally thought it should be tied in with event import on PlaceCal and or any updates to Partners etc, but that would probably be too many builds. @GeorgieMcVicar also knows how to trigger manually if a specific update needs to be releassed.

There is a (PWA ticket)[https://github.com/GenderedIntelligence/the-trans-dimension/issues/17] that will include grabbing up to date data between builds too.

**Comment by katjam** [comment]
@ivan-kocienski-gfsc I still think this cron could belong on the PlaceCal server... especially if you already run any on there.

Ideally I think trigger 2 builds per day so we don't creep up on build mins.

**Comment by kimadactyl** [comment]
it feels really bad from a devops perspective to do that to me. i think the retriggers need to happen in the same place as the rest of the code base esp as we are hoping to make it a boilerplate repo

**Comment by katjam** [comment]
I know we disagree about this. My logic is that the rebuild only needs to
happen if the data changes. So like the API pushes out to its clients when
it has new data.

I do understand what you are saying though. Currently we do not have
requirement for a server to do anything else besides the static hosting
apart from the form submit which I think is a "sleeping lambda" that wakes
up when poked. So if we do want this cron and to have it somewhere other
than Place all, we'll need to spin up another service for it.

**Comment by kimadactyl** [comment]
Ah ok i understand that because it's not a cron tho - isn't that more of a webhook? 

That's a nice feature to have but it should go on the backlog and get prioritsed and i'm not sure how much time we have for it at the moment.

Tbh I could just run a cron on my local machine?

**Comment by kimadactyl** [comment]
Feel like this is also time to summon @erbridge

**Comment by katjam** [comment]
Basically I worked out that the easiest way to get the site to rebuild with up to date data a couple times a day was to trigger a build through that netlify build hook from a Cron.

And the most obvious place to me for that Cron was the PlaceCal server that hosts the data. I assumed also that there were already crons running to for example scrape for calendar data and I thought it would sit nicely alongside those.

The only slight issue is we don't want to do it too often because of free build minutes 

There is another ticket about fetching live data from the api whenever the app is used online so when that is done then this becomes less of an issue but either way, we do want the static build assets to be reasonably up to date.

**Comment by kimadactyl** [comment]
I mean feel free to try it! I'm just very nervous having a mission-critical script running in a cron that is not documented anywhere and not part of the dokku containerisation.

I would note that Cloudflare has unlimited free build minutes as far as I can tell and also has built in Cron.

https://developers.cloudflare.com/workers/platform/cron-triggers

**Comment by kimadactyl** [comment]
Yeah -  I think we should move this to Cloudflare. The free package is orders of magnitude better than netlify with unlimited build minutes, built in cron, proper multi auth login, better stats, free functions if we need them, and more generous bandwidth limit. TSN have decided we are collectively happy with CF now they have in fact, booted the bad site, esp given it's not like other providers are queuing up to say that they wouldn't allow that kind of content. I personally don't think it's worth us thinking about it any further than that but open to other opinions. This just solves several very real problems for us that we have right now and we are short on time to get this done as it is.

**Comment by erbridge** [comment]
GitHub Actions also works for this stuff. You can tell it to run things on a schedule, so a simple action that just runs that `curl` script twice a day might do all we need. The usual downside is that scheduled actions turn off after 60 (?) days of no repo activity, but I don't think that's an issue here from the context.

**Comment by erbridge** [comment]
Happy to write that if it's the approach we want to take. 15 minute job, if that.

**Comment by erbridge** [comment]
There we go. Less than 10 minutes :)

https://github.com/GenderedIntelligence/the-trans-dimension/pull/298

**Comment by kimadactyl** [comment]
I would still prefer the Cloudflare route for reasons stated. Happy for this as a stopgap but I think it's in danger of getting increasingly bandaid-y. I also think once it's running it is very likely it doesn't get touched for 2 months.

**Comment by kimadactyl** [comment]
I'll open a new issue for cloudflare
