### ISSUE TITLE
Employ environment variables to configure critical values

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [GenderedIntelligence/the-trans-dimension#299]
## Description

Some values are hardcoded into the source like which URL to use when accessing PlaceCal API (this may be the only one). This is not good as it is a mental burden on the developer to remember to change these values when working on various aspects of the code. It also makes pushing to github repo error prone as there is no easy way to get the CI server to use a particular value.

## Plan
- [ ] Investigate environment variable libraries in elm/js ([dotenv](https://github.com/motdotla/dotenv) looks promising)
- [ ] Import environment from JS to elm on local dev server and build run
- [ ] Use configured URL
- [ ] Configure CI to set specific value on build, test and deploy

**Comment by erbridge** [comment]
I think the Elm thing for this is [`elm-constants`](https://github.com/jaredramirez/elm-constants), btw.

**Comment by ivan-kocienski-gfsc** [comment]
So far I have identified the following fields
```
CANONICAL_URL (in /src/Site.elm)
PLACECAL_API (in /src/Api.elm)
JOIN_US_FUNCTION_URL (in /src/Page/JoinUs.elm)

```

Maybe some things from `/src/Copy/Text.elm`?
