### ISSUE TITLE
builds main at timed interval

### ISSUE THREAD

**Issue by aaaaargZombies** [GenderedIntelligence/the-trans-dimension#325]
## Acceptance Criteria

- [ ] The site builds at timed intervals
- [ ] We do not exceed cloudflare free build quota

## Plan

- [ ] Check allowed builds in free cloudflare tier
- [ ] Use approx 2/3 of them in auto build and save rest for PRs

Just needs the job uncommenting when we are ready in `.github/workflows/build.yml`

**Comment by aaaaargZombies** [comment]
for Ivan - with cloudflare we get 500 builds a month of the free tier, it doesn't seem to be limited by minutes (which is lucky in this case)

So the real question is probably what will placeCal tolerate?

**Comment by katjam** [comment]
> I was more thinking about the error logging service that Ivan mentioned in standup.

Yeah - I wasn't sure if we were sure what the issue was. I hope hitting the API does not throw errors - if it does we might need some better handling.

**Comment by kimadactyl** [comment]
Every 2 hours would use 360 builds - is that cutting it a bit fine?

I propose every 3 hours - be about 240 builds a month
