### ISSUE TITLE
[Bug]: Event pages are taking nearly half a second to build which is making the build time out

### ISSUE THREAD

**Issue by kimadactyl** [GenderedIntelligence/the-trans-dimension#348]
## Description

Builds are currently taking 40 minutes plus which is meaning [Cloudflare is timing out the build](https://developers.cloudflare.com/pages/platform/limits/Builds).

On looking at the log it seems the reason for this is that individual event pages are taking 450ms+ to build - this seems really long. We are about to get an influx of many new events too so this issue needs resolving before launch.

## Steps to reproduce

1. Attempt to build the site on Cloudflare
2. Build fails

## Plan

- [x] Temporarily set event start date to 1 Sept 2022 end date 30 June 2023 https://github.com/GenderedIntelligence/the-trans-dimension/pull/350/files
- [x] Try  - Load single event data from the all events endpoint
- [x] #351
- [ ] If that doesn't work, consider caching https://github.com/GenderedIntelligence/the-trans-dimension/issues/269
- [ ] When resolved, add info in the shiny new GFSC incident log

**Comment by katjam** [comment]
I'm wondering if we should reconsider the approach of getting event data for single events from the list of all events rather than follow traditional pattern of loading each one individually.

Need to check if the API endpoint for all events have all the data we need for that?

**Comment by katjam** [comment]
related to: https://github.com/GenderedIntelligence/the-trans-dimension/issues/269

**Comment by katjam** [comment]
Looking at the code, the API request is only being made on the all Events endpoint. It's the static build of each individual event page taking the time. 

Going to try a strategy of loading all dates for all events but using a filtered list for individual event pages then live load from API if 404 on event link.

**Comment by katjam** [comment]
Won't fix. Solved by caching first fetch during build.
