### ISSUE TITLE
Set up notifications when builds fail

### ISSUE THREAD

**Issue by kimadactyl** [GenderedIntelligence/the-trans-dimension#349]
## Description

Builds are currently silently failing 

## Plan

- [ ] Make sure project devs (who?) get notified on fail. Email or Discord webhook?
- [ ] Document how to change this

**Comment by kimadactyl** [comment]
Spend 20 mins on this then put on backlog

**Comment by ivan-kocienski-gfsc** [comment]
So it looks like cloudflare don't have any native options for doing this so it may be worth parking and coming back to it later on

**Comment by kimadactyl** [comment]
webhooks look nontrivial to set up - removing from the milestone

**Comment by katjam** [comment]
This is the proposed solution https://github.com/WalshyDev/cf-pages-await from https://community.cloudflare.com/t/notifications-for-failed-deployments/420586

**Comment by katjam** [comment]
So @kimadactyl I guess we can close this since you found: https://developers.cloudflare.com/notifications/notification-available/#pages

**Comment by katjam** [comment]
Maybe let's wait until you get a success e2e test... should not take long because it's failing a couple times a day.

**Comment by kimadactyl** [comment]
done
