### ISSUE TITLE
[Bug]: All partners map is being stretched out to show Exeter

### ISSUE THREAD

**Issue by kimadactyl** [GenderedIntelligence/the-trans-dimension#352]
## Acceptance Criteria

- [ ] If a partner has a service area, they do not have a pin in the map.

Note: The rationale for this is that only venues where people can go should be pinned, not head offices. The Place Cal data is structured such that if an organisation services an area, they list themselves with a service area. If an organisation is a venue that people can go to, they do not list themselves as a service area.

## Description

The map is being stretched out to Exeter as the LGBT consortium have a postal address there. I think it should just focus on London.

<img width="1191" alt="Screenshot 2022-10-27 at 15 04 37" src="https://user-images.githubusercontent.com/511734/198307186-b295a4dc-0f43-47b0-95a3-0d1106378a9b.png">

**Comment by ivan-kocienski-gfsc** [comment]
This is a problem that is on PlaceCal as that is where the scope of the query is defined. TransDim just shows partners by "location"

**Comment by kimadactyl** [comment]
I don't think this is a problem PlaceCal's end - it's nice to know the addresses for places. It's just we don't want that address to show up on the map if it's a service area-based org.

**Comment by kimadactyl** [comment]
yes - so the point of this ticket is that if there is a service area, don't show the address pin in the all partners map?

**Comment by ivan-kocienski-gfsc** [comment]
okay i understand now, thanks for clearing that up
