### ISSUE TITLE
Weds 2 Nov: Flip the go live switch

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#354]
## Description
DNS config for transdimension.uk

## Plan
- [x] Point http(s)://transdimension.uk and http(s):www./transdimension.uk at cloudflare instance
- [x] Set canonical to https://transdimension.uk (in code & dns redirect)
- [x] info@transdimension.uk -> admin@genderedintelligence.co.uk email redirect
- [x] Build site
- [x] Manual test site meta urls
- [x] Manual test join us form submission
- [x] Manual test "everything else"
- [ ] MORE tbc (please add)

**Comment by katjam** [comment]
@kimadactyl This suggests we have to manage the DNS in cloudflare.

**Comment by kimadactyl** [comment]
ill update the nameservers :)

**Comment by katjam** [comment]
So I guess we only need new nameservers on transdimension.uk

**Comment by katjam** [comment]
Yes, what you said. I'll go ahead with registering and let you know.

**Comment by katjam** [comment]
The Free tier also says for personal or hobby projects but I've not read the terms in detail so I guess we are OK until someone tells us to stop.

**Comment by katjam** [comment]
OK - cloudflare tried to automatically grab the www A record. which I guess is what happened before. I'll add manually now and see what happens.

**Comment by kimadactyl** [comment]
yeah exactly that haha it dutifully copied over the netlify config

**Comment by ivan-kocienski-gfsc** [comment]
I have checked the remaining items and all works as intended.
