### ISSUE TITLE
[Bug]: OG image not showing up on Twitter

### ISSUE THREAD

**Issue by kimadactyl** [GenderedIntelligence/the-trans-dimension#375]
## Description

Posting the link to Twitter doens't show a nice og:image

https://twitter.com/gfscstudio/status/1591378319542349824

I think it needs to be an absolute URL and not a relative one? Showing as:

`<meta property="og:image" content="/images/logos/tdd_logo_with_strapline_on_darkBlue.png" />`

<img width="844" alt="Screenshot 2022-11-12 at 10 33 42" src="https://user-images.githubusercontent.com/511734/201470190-42b11431-d1c7-470e-ad37-d8fb90ea8fbc.png">

**Comment by kimadactyl** [comment]
It seems to work in Discord and WhatsApp - assume either Twitter is pickier or they're having tech issues.

**Comment by katjam** [comment]
As far as I am aware, meta links must all be absolute. Facebook ones also need the cache priming sometimes.

There was an issue about replacing all meta links with the canonical URL when we swapped. Did it get closed without completing? I'm on my phone but will dig out later and link. @katjam (reminder)

**Comment by kimadactyl** [comment]
Maybe Cloudflare isn't loading in the canonical URL properly - esp if there was an absolute link there before?

**Comment by katjam** [comment]
I'll take a look.
