### ISSUE TITLE
[Bug]: og:image is not displaying

### ISSUE THREAD

**Issue by kimadactyl** [GenderedIntelligence/the-trans-dimension#385]
## Description

Noticed this isn't showing up in Twitter: https://twitter.com/gfscstudio/status/1641772440714985504

On inspection I think there's a missing `/` after the domain: https://www.opengraph.xyz/url/https%3A%2F%2Ftransdimension.uk%2F

`https://transdimension.ukimages/logos/tdd_logo_with_strapline_on_darkBlue.png`

**Comment by katjam** [comment]
Added trailing slash to env vars and triggered rebuild
![image](https://user-images.githubusercontent.com/861172/229304961-1acc6e56-a152-4b2e-861e-0bda5a5d1934.png)

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/229306254-4d0ae71c-fe54-48b3-9565-6c0fc04d0b51.png)
