### ISSUE TITLE
[Bug]: Trans housing justice workshops not showing up

### ISSUE THREAD

**Issue by kimadactyl** [GenderedIntelligence/the-trans-dimension#388]
## Description

> At GI we're doing a series of [trans housing justice workshops](https://www.eventbrite.co.uk/e/trans-housing-justice-workshop-community-dinner-tickets-611052794357). I believe previous dates have been automatically scraped and appeared on Trans Dimensions.
>
> I just wanted to ask if you could please ensure the newly added date on June 8 also gets added (we added it to the options due to demand) as currently it's not showing up.

## Steps to reproduce
1. What you did first
1. What you did next

## Platform (if relevant)
What device and browser were you using?

## Notes

Seems to be importing via [this calendar](https://admin.placecal.org/calendars/138/edit)

**Comment by katjam** [comment]
@ivan-kocienski-gfsc I think you are in progress with investigating this. If so, please assign to yourself and add your investigations here - they might get lost in discord.

**Comment by kimadactyl** [comment]
Note its possible they just didnt wait long enough

**Comment by ivan-kocienski-gfsc** [comment]
Looking into this and i can't seem to pin down which calendar this should be importing from (on production).

(i am trying to look for the URL but not finding anything)

**Comment by kimadactyl** [comment]
i'll forward you the email and you can ask!

**Comment by kimadactyl** [comment]
or @GeorgieMcVicar do you know?

**Comment by ivan-kocienski-gfsc** [comment]
I have re-imported the calendar through the console and it seems to be importing that event now.

Wait until it turns up on trans dimension site and this issue can be closed.

**Comment by kimadactyl** [comment]
Shall we close this as it's way in the past and the events wouldn't get imported now anyway?

**Comment by GeorgieMcVicar** [comment]
Yep happy to.

**Comment by katjam** [comment]
Marking as Won't fix & Not verifying as this can't be checked now since the events are well in the past.
