### ISSUE TITLE
[Bug]: contact from partner by tag not resolving (probably a missing address?)

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#400]
Site build failing

```
18:07:54.891 | I encountered some errors while decoding this JSON:
-- | --
18:07:54.891 |  
18:07:54.891 | At path /data/partnersByTag/24/contact
18:07:54.891 |  
18:07:54.891 | I expected an object here, but instead found this value:
18:07:54.892 |  
18:07:54.892 | null
18:07:54.892 |  
18:07:54.892 | At path /data/partnersByTag/24/contact
18:07:54.892 |  
18:07:54.892 | I expected an object here, but instead found this value:
```

**Comment by katjam** [comment]
@GeorgieMcVicar Wanted to give you a heads up that the Trans Dimension site is failing to re-build with new data since yesterday, It looks like maybe some contact details missing for a partner, if that rings a bell with any edits you've done recently.

I'll look into it tomorrow. It should not be possible to save data in PlaceCal that the site can't handle so I'll fix it on the Trans Dimension side, regardless.

**Comment by GeorgieMcVicar** [comment]
Thanks - let me know how it goes :)

**Comment by katjam** [comment]
It looks like the issue is with `Material Grrrlz` data. I have made a fix locally that works but it has also made me look into where and how we display those contact details. So I don't want to rush out the fix. I will release tomorrow.

**Comment by katjam** [comment]
I can't immediately see what the difference with their data is. They do have contact details, but not coming through.

**Comment by katjam** [comment]
There is a problem with the data coming from PlaceCal, I think. I have amended the code to expect Contact details to maybe not be there - but in this case They are there, just not coming through.

![image](https://github.com/GenderedIntelligence/the-trans-dimension/assets/861172/6aa9d5d2-172b-4b6f-9838-2cc1462424f1)

![image](https://github.com/GenderedIntelligence/the-trans-dimension/assets/861172/f66e4cc0-9b3e-46c3-9cb7-40acd0b32234)

**Comment by katjam** [comment]
I am hoping that @kimadactyl agrees, I plan to merge this "fix" that allows the details to be missing so that the build can continue to work. Next week we'll make some time to look at the issue in PlaceCal.

**Comment by kimadactyl** [comment]
Agree yes this seems important to fix! Maybe let's start a mini milestone?
