### ISSUE TITLE
[Bug]: CI is building inconsistently

### ISSUE THREAD

**Issue by kimadactyl** [GenderedIntelligence/the-trans-dimension#404]
## Description

Site is failing about half the time due to an Elm compilation error. This is significantly reducing our quality of life as our notifications are throwing a lot of false positives, and information updates are inconsistent.

Currently it is as below, but I think the package name has shifted a few times.

Some idea of what might be causing it and a suggested fix is here: https://discourse.elm-lang.org/t/problem-building-dependencies-error-in-pipeline-solved/8755

```
09:10:12.800 | -- PROBLEM BUILDING DEPENDENCIES -----------------------------------------------
-- | --
09:10:12.800 |  
09:10:12.801 | I ran into a compilation error when trying to build the following package:
09:10:12.801 |  
09:10:12.801 | elm/regex 1.0.0
09:10:12.801 |  
09:10:12.801 | This probably means it has package constraints that are too wide. It may be
09:10:12.802 | possible to tweak your elm.json to avoid the root problem as a stopgap. Head
09:10:12.802 | over to https://elm-lang.org/community to get help figuring out how to take this
09:10:12.802 | path!
09:10:12.802 |  
09:10:12.802 | Note: To help with the root problem, please report this to the package author
09:10:12.802 | along with the following information:
09:10:12.802 |  
09:10:12.802 | elm/core 1.0.5
09:10:12.802 |  
09:10:12.802 | If you want to help out even more, try building the package locally. That should
09:10:12.803 | give you much more specific information about why this package is failing to
09:10:12.803 | build, which will in turn make it easier for the package author to fix it!
09:10:12.803 |  
09:10:12.803 | Compilation failed.
09:10:12.803 |  
09:10:12.818 | Failed: build command exited with code: 1
09:10:13.724 | Failed: error occurred while running build command
```

## Steps to reproduce

View Cloudflare build logs on fail

**Comment by kimadactyl** [comment]
@katjam - link in issue ticket suggests a solution but it's out of my depth

**Comment by katjam** [comment]
Thanks. I did used to use that Netlify cache thing to solve the problem there, but it did stop working a couple times / changed server spec.

For this I am wondering if we pull back to building twice a day. At the moment it's every 3 hours which shouldn't be overlapping - but maybe it overlaps with someone else on same machine? I have no idea how cloudflare allocates these build servers but the problem does seem a lot more frequent than it was on netlify.

**Comment by kimadactyl** [comment]
I think it's just that there's 3 projects in `elm-stuff` that are clashing, no? thats what the link seemed to suggest to me, anyway

**Comment by katjam** [comment]
Looks like that update happened in v3.0 - so for now I'll fix the event window import #391 and we should do an experiment with upgrading to v3.0 when we integrate Manchester because it seems like it'll address a couple things for us.

**Comment by katjam** [comment]
closing as superseded by: #412

**Comment by katjam** [comment]
Verified. Have raised a bug to deal with Time #449 - but otherwise build seems to be working well. Time will tell once merged.
