### ISSUE TITLE
Replace old GI logo with new GI logo

### ISSUE THREAD

**Issue by studiosquid** [GenderedIntelligence/the-trans-dimension#406]
## Description
Replace old GI logo with new one

## Plan
- [ ] White logo on About page
- [ ] Pink logo in footer

## SVGs are below
![TD_GI_Logo_Pink](https://github.com/user-attachments/assets/2c81b4ac-ae57-40ed-aeca-682c91387a28)
![TD_GI_Logo_White](https://github.com/user-attachments/assets/96245866-9172-4dfc-b9b4-869b4cdca70c)

**Comment by katjam** [comment]
Verified on staging:
![image](https://github.com/user-attachments/assets/45058bef-db4a-4d45-b8f4-766a491c4d83)

![image](https://github.com/user-attachments/assets/410be1d4-8273-4e30-8129-26d2e6cb728e)
