### ISSUE TITLE
Fix registered office address

### ISSUE THREAD

**Issue by studiosquid** [GenderedIntelligence/the-trans-dimension#407]
## Description
The registered office on Trans Dimension is wrong (this was flagged as an issue on the GI website it is also wrong here). 

## Plan
- [ ] Add an a to 200 — should read "200a Pentonville Road" not "200 Pentonville Road"

**Comment by katjam** [comment]
Verified on staging
![image](https://github.com/user-attachments/assets/40d0989c-7057-4847-aca2-30ab2ed78430)
