### ISSUE TITLE
Upgrade to Elm Pages 3 and update depends

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#412]
## Description
Upgrade out framework & dependencies

## Acceptance Criteria

- [ ] elm pages is version `3.0.x`
- [ ] node is version 20
- [ ] node scripts run without error (postinstall, start, build, format, test)
- [ ] https://github.com/GenderedIntelligence/the-trans-dimension/issues/404
- [ ] site builds and deploys without error
- [ ] pages are identical to release on https://transdimension.uk

## Plan first
- [x] Upgrade other deps
- [x] Upgrade to `elm-pages v3`
- [x] move source files
- [x] move theme and route files out to get index working in v3
- [x] replace Path with UrlPath
- [x] replace Cmd with Effect
- [x] amend script/src/AddRoute.elm & AddStaticRoute to use elm-css
- [x] Amend default mainfest in app/Api.elm ? This is new here in v3 - check where was before

## Considerations
-  migrate Decoders
- migrate DataSource
- amend Route exports for data and ActionData

## Initial port of Theme & Routes
- [x] About
- [ ] 404/error
- [x] Events (index & single)
- [x] Partners index
- [x] Partner single
- [x] Index
- [ ] JoinUs
- [x] News index
- [x] News item
- [x] Add stock images to News Item
- [x] Add Events back into `Partner_.elm` pages
- [x] Privacy
- [x] Meta / Head
- [x] #432

## Next
- [x] Clear out with elm-review
- [ ] Review efficiency of build and data loading in context of below list
- [ ] Update readme (see notes below)

## Review issues after upgrade
Some of them might be able move to AC

- [ ] https://github.com/GenderedIntelligence/the-trans-dimension/issues/391
- [ ] https://github.com/GenderedIntelligence/the-trans-dimension/issues/386
- [ ] https://github.com/GenderedIntelligence/the-trans-dimension/issues/364
- [ ] https://github.com/GenderedIntelligence/the-trans-dimension/issues/351
- [ ] https://github.com/GenderedIntelligence/the-trans-dimension/issues/348
- [ ] https://github.com/GenderedIntelligence/the-trans-dimension/issues/296
- [ ] https://github.com/GenderedIntelligence/the-trans-dimension/issues/269
- [ ] https://github.com/GenderedIntelligence/the-trans-dimension/issues/268
- [ ] https://github.com/GenderedIntelligence/the-trans-dimension/issues/210
- [ ] https://github.com/GenderedIntelligence/the-trans-dimension/issues/72
- [ ] https://github.com/GenderedIntelligence/the-trans-dimension/issues/17

## Readme

- [ ] Update any refs and links to elm-pages v3
- [ ] structure of code updated e.g. `app/` is for files specific to elm-pages our custom additional modules in `src/`

**Comment by katjam** [comment]
Suggested upgrade path for v2 to v3:
https://discourse.elm-lang.org/t/introducing-elm-pages-v3-full-stack-elm-and-scripts/9185/12

elm-pages v3 docs:
https://elm-pages.com/docs/

**Comment by katjam** [comment]
removing OptimizedDecoder's and replacing with plain Decoders, and using the new `BackendTask` and `FatalError` APIs instead of `DataSource`

**Comment by kimadactyl** [comment]
ahha i didnt see this ticket! now have a really good idea what this is taking to get done, wow its a lot!

**Comment by katjam** [comment]
This needs further work, but much improvement.

Further work:
- node test script broken #446
- build warning on time fetch #449
