### ISSUE TITLE
Use cached data for Partner & Event

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#432]
## Acceptance Criteria

- [ ] During build, if the data has already been fetched from the API, the data is fetched from local `.json` rather than remote `graphQL`
- [ ] The PlaceCal API is not being hammered during a build
- [ ] The build takes less than 1 minute

**Comment by katjam** [comment]
There are a lot of ways you could approach something like that. For example, you can use BackendTask.Custom to create your own cache layer in front of HTTP or GraphQL requests. You could do something as simple as checking if the query string is exactly the same, and looking up a JS object to get a stored response if it has already been executed. Or you could use BackendTask.Custom to call out to some NPM package for performing cached GraphQL queries or HTTP queries.
npm
[make-fetch-happen](https://www.npmjs.com/package/make-fetch-happen)
Opinionated, caching, retrying fetch client. Latest version: 13.0.1, last published: 4 months ago. Start using make-fetch-happen in your project by running `npm i make-fetch-happen`. There are 298 other projects in the npm registry using make-fetch-happen.
Image
You could also do some build-time step that executes a distinct set of GraphQL queries all upfront, and then reach into that data (either a JSON file or something else). BackendTask is very customizable since you can perform arbitrary effects there, even writing to files with BackendTask.File, so you could build a caching mechanism at that layer as well.

**Comment by kimadactyl** [comment]
confirmed its a one liner to add a GET endpoint to existing api

**Comment by katjam** [comment]
Build takes a bit more than a minute but is vastly improved. Time will tell once merged to live, but verifying for now based on dev and staging experience.
